### ISSUE TITLE
目录生成时缺失中英文摘要以及未来与展望，并且宋体\textbf命令无法生效

### ISSUE THREAD

**Issue by Joeless** [yusanshi/hnuthesis#11]
@yusanshi 你好，感谢你的模版提供，让我省去了不少格式麻烦
目前我遇到了录生成时缺失中英文摘要以及未来与展望，并且宋体\textbf命令无法生效两个问题，请问我该如何解决呢

**Comment by moshimo2019** [comment]
用v1.0.0版本的，
宋体加粗用黑体代替 模板里面\setCJKmainfont{[simsun.ttc]}替换成 \setCJKmainfont[BoldFont={[simhei.ttf]}]{[simsun.ttc]}

**Comment by yusanshi** [comment]
谢谢 @moshimo2019 ，以及抱歉忘了处理这个 issue，@Joeless 请使用最新的代码。
