### ISSUE TITLE
插图索引跨章节间距过大

### ISSUE THREAD

**Issue by Aristozhang** [yusanshi/hnuthesis#12]
图 1.1   这是第一章节的第一张图................2 
图 1.2   这是第一章节的第二张图................5

图 2.1    这是第二章节的第一张图..............10 
如上面例子，同一章节的插图索引行间距和不同章节的插图索引行间距不一样，比如上面图1.1和图1.2的行间距与图1.2和图2.1的行间距不同。请问这个怎么解决？

**Comment by yusanshi** [comment]
参考：<https://tex.stackexchange.com/questions/784/how-to-change-the-line-spacing-in-my-list-of-figures>

在 `\begin{document}` 前加入：
```tex
\newcommand*{\noaddvspace}{\renewcommand*{\addvspace}[1]{}}
\addtocontents{lof}{\protect\noaddvspace}
```


---

前：
![image](https://user-images.githubusercontent.com/36265606/236671294-21939300-a7f2-4f6c-86ce-3fcf2b987ab3.png)


后：
![image](https://user-images.githubusercontent.com/36265606/236671262-768ebdb8-ed85-4e87-8c83-0621d550cf04.png)
