### ISSUE TITLE
引用的格式更改

### ISSUE THREAD

**Issue by JiangZhengtao1** [yusanshi/hnuthesis#14]
在hnuthesis.cls文件中作如下修改：

搜索：  \renewcommand\bibfont{\setfontsize{10.5bp}[20bp]}

修改为字体大小为12磅（小四）、行间距为20磅：  \renewcommand\bibfont{\normalfont\fontsize{12pt}{20pt}\selectfont}

**Comment by yusanshi** [comment]
感谢您的发现！我检查了下撰写规范，确实应该按你说的这样。要不你直接提个 Pull Request？

**Comment by JiangZhengtao1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢作者回复，好的。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月22日 10:09
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yusanshi/hnuthesis] 引用的格式更改 (Issue #14)
        
      
    
  
  
感谢您的发现！我检查了下撰写规范，确实应该按你说的这样。要不你直接提个 Pull Request？
