### ISSUE TITLE
目录页面缺少内容

### ISSUE THREAD

**Issue by 8pterosaur** [yusanshi/hnuthesis#17]
在[《湖南大学研究生学位论文撰写规范》](http://gra.hnu.edu.cn/info/1276/3444.htm)中，目录页面缺少红框内容：
![目录](https://github.com/yusanshi/hnuthesis/assets/115774637/59b5a4f1-8230-41ae-9ffe-b57993992bf7)

由于对latex的的语法格式不熟悉，烦请作者帮忙修复
谢谢

**Comment by yusanshi** [comment]
感谢提出问题，我发现 #16 已经提出了针对这个问题的 PR, 但我之前忘了合并。已合并，请使用最新 main branch 的代码。

![2024-02-26_22-49](https://github.com/yusanshi/hnuthesis/assets/36265606/0dc20889-7406-4f38-b845-fa9028a60b27)

**Comment by 8pterosaur** [comment]
好的，非常感谢作者的及时回复。
目前还存在另外一个问题：标题英文不是Times New Roman
为了不与这个issue冲突，我重开了[#18标题英文字体格式不正确](https://github.com/yusanshi/hnuthesis/issues/18#issue-2155491971)，麻烦作者能帮忙看下吗？
