### ISSUE TITLE
目录处无绪论之前的页面

### ISSUE THREAD

**Issue by JXJiangXu** [yusanshi/hnuthesis#19]
![image](https://github.com/yusanshi/hnuthesis/assets/50006261/e67049e1-551d-4cda-b566-925d7de0618a)
有没好哥哥教教如何调整

**Comment by JXJiangXu** [comment]
目前是
![image](https://github.com/yusanshi/hnuthesis/assets/50006261/e79ddcb4-6c1f-4fe5-aae5-1a0c07f5ab6f)

**Comment by yusanshi** [comment]
你应该是在使用 overleaf 吧？请按照最新的 <https://github.com/yusanshi/hnuthesis?tab=readme-ov-file#1-本地编译版本最新推荐>。

或者用最新的 <https://github.com/yusanshi/hnuthesis/blob/main/hnuthesis.cls> 文件覆盖更新 overleaf 项目文件夹中的同名文件。

**Comment by JXJiangXu** [comment]
大大，还是会少目录本身，这个能怎么调吗

**Comment by yusanshi** [comment]
> 还是会少目录本身
规范里的目录没有要求有“目录”本身吧？！

这是规范里的：

![image](https://github.com/yusanshi/hnuthesis/assets/36265606/9c51c920-200f-40cf-9d44-6c696910c097)

这是模板目前的：

![image](https://github.com/yusanshi/hnuthesis/assets/36265606/3394db8c-824d-481b-9493-23496fb5f975)

所以目前的应当是ok的

**Comment by JXJiangXu** [comment]
嗷嗷嗷，谢谢大大
