### ISSUE TITLE
文献引用一直报错

### ISSUE THREAD

**Issue by guixiaole** [yusanshi/hnuthesis#2]
想问一下，使用vscode，文献引用一直报错。使用的是demo中的示例。报错信息Citation `he2016deep' on page 2 undefined.

**Comment by yusanshi** [comment]
你直接在命令行里 `latexmk -xelatex -shell-escape main.tex` 会有问题吗？

**Comment by guixiaole** [comment]
> 你直接在命令行里 `latexmk -xelatex -shell-escape main.tex` 会有问题吗？

直接在命令行没有问题，vscode的自动保存有问题。引用会显示？

**Comment by yusanshi** [comment]
那说明是 vscode 里 latex workshop 插件的配置有问题，试试这个：

（把以下内容放到 `.vscode/settings.json` 里）

```json
{
    "latex-workshop.latex.recipes": [
        {
            "name": "latexmk with xelatex",
            "tools": ["latexmk_xelatex"]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk_xelatex",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-file-line-error",
                "-halt-on-error",
                "-interaction=nonstopmode",
                "-synctex=1",
                "-shell-escape",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ],
            "env": {}
        }
    ],
    "latex-workshop.latex.build.forceRecipeUsage": true
}
```

**Comment by guixiaole** [comment]
> 那说明是 vscode 里 latex workshop 插件的配置有问题，试试这个：
> 
> （把以下内容放到 `.vscode/settings.json` 里）
> 
> ```json
> {
>     "latex-workshop.latex.recipes": [
>         {
>             "name": "latexmk with xelatex",
>             "tools": ["latexmk_xelatex"]
>         }
>     ],
>     "latex-workshop.latex.tools": [
>         {
>             "name": "latexmk_xelatex",
>             "command": "latexmk",
>             "args": [
>                 "-xelatex",
>                 "-file-line-error",
>                 "-halt-on-error",
>                 "-interaction=nonstopmode",
>                 "-synctex=1",
>                 "-shell-escape",
>                 "-outdir=%OUTDIR%",
>                 "%DOC%"
>             ],
>             "env": {}
>         }
>     ],
>     "latex-workshop.latex.build.forceRecipeUsage": true
> }
> ```

谢谢。有用。
