### ISSUE TITLE
PDF to Word 链接已失效

### ISSUE THREAD

**Issue by Astro-Lee** [yusanshi/hnuthesis#3]
求解决办法

**Comment by yusanshi** [comment]
我这边看还是可以的

![image](https://user-images.githubusercontent.com/36265606/155871289-fd45d287-65db-4d66-94dd-d77daf1aedea.png)

**Comment by Astro-Lee** [comment]
我换了一下设备，现在可以打开了。O(∩_∩)O谢谢！
