### ISSUE TITLE
图片和文字之间相隔太大

### ISSUE THREAD

**Issue by SuQiucheng** [yusanshi/hnuthesis#5]
您好，请问为啥文字和图片下方隔的那么大呢？
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/37232610/161381037-5d05c1e0-fff1-4482-ab66-e8a92d9d6a2d.png">

**Comment by yusanshi** [comment]
似乎还好？！🤣 你手动用 `\vspace{-2.5mm}` 调整下吧
<br>
![image](https://user-images.githubusercontent.com/36265606/161384151-0033d66b-90c8-4a25-a880-01fe1c04cc8f.png)
