### ISSUE TITLE
加入更多章节导致空白页

### ISSUE THREAD

**Issue by gongjun136** [yusanshi/hnuthesis#6]
当我加入更多章节，在插表索引和绪论之间有一个空白页，请问这个什么导致的
![image](https://user-images.githubusercontent.com/73570451/204947604-a213f821-8c7a-45bc-8dc4-2e18e926f385.png)

**Comment by yusanshi** [comment]
这个应该是预期行为，目的是使得文档在双面打印装订时，附图索引页、目录页等总是会在右手侧。

如果你不希望这样，可以在文档靠前位置加入：
```tex
\let\cleardoublepage\clearpage
```

比如：

![image](https://user-images.githubusercontent.com/36265606/204951954-a74a2655-bd51-4098-a315-702ee8124da4.png)


Refer: 
<https://tex.stackexchange.com/questions/69184/remove-blank-page-between-list-of-figures-and-list-of-tables>
<https://tex.stackexchange.com/questions/495335/how-to-remove-the-empty-page-that-is-placed-after-the-toc-list-of-figures-and-l>

**Comment by gongjun136** [comment]
确实是这样的，受教了，感谢[抱拳]




3592754223
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yusanshi/hnuthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yusanshi/hnuthesis] 加入更多章节导致空白页 (Issue #6)





 
这个应该是预期行为，目的是使得文档在双面打印装订时，附图索引页、目录页等总是会在右手侧。
 
如果你不希望这样，可以在文档靠前位置加入：
 \let\cleardoublepage\clearpage
 
比如：
 

 
Refer:
 https://tex.stackexchange.com/questions/69184/remove-blank-page-between-list-of-figures-and-list-of-tables
 https://tex.stackexchange.com/questions/495335/how-to-remove-the-empty-page-that-is-placed-after-the-toc-list-of-figures-and-l

**Comment by gongjun136** [comment]
还有一个细节，就是在撰写规范中，每个章节的数字应该是times new roman字体，文字是黑体，模板中都变成了黑体，因为对latex不是特别熟悉，想咨询下，这个该怎么修改过来呢





3592754223
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yusanshi/hnuthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yusanshi/hnuthesis] 加入更多章节导致空白页 (Issue #6)





 
这个应该是预期行为，目的是使得文档在双面打印装订时，附图索引页、目录页等总是会在右手侧。
 
如果你不希望这样，可以在文档靠前位置加入：
 \let\cleardoublepage\clearpage
 
比如：
 

 
Refer:
 https://tex.stackexchange.com/questions/69184/remove-blank-page-between-list-of-figures-and-list-of-tables
 https://tex.stackexchange.com/questions/495335/how-to-remove-the-empty-page-that-is-placed-after-the-toc-list-of-figures-and-l

**Comment by gongjun136** [comment]
好滴，没事，那就这样用吧，影响也不大，感谢您的回答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月1日(周四) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yusanshi/hnuthesis] 加入更多章节导致空白页 (Issue #6)




 
抱歉我没摸清怎么实现中文和英文(及数字)用不同的字体。可能一个比较脏的方法是提取黑体的中文部分和Times字体的英文数字部分组合成新字体。
