### ISSUE TITLE
中文文献引用问题

### ISSUE THREAD

**Issue by yakunouyang** [yusanshi/hnuthesis#7]
首先感谢此项目，可以用latex写学位论文了🙏

```latex
@phdthesis{libaiThesis,
  type = {{博士}},
  title = {{复杂约束下自动驾驶车辆运动规划的计算最优控制方法研究}},
  author = {李, 柏},
  year = {2018},
  langid = {chinese},
  school = {浙江大学},
}
```

在使用中发现了几个问题，主要是引用中文参考文献时，使用上述代码引用，效果如下图所示：

<img width="439" alt="image" src="https://user-images.githubusercontent.com/85840949/218855110-32e3fc08-b34d-4102-bc24-ba091d2fec98.png">

1. 当author中出现姓名用`,`区分时名字部分会乱码
2. bib文件中语言字段是`langid`和`language`，而源码中使用`lang`进行判断，使用`langid={chinese}`无效，导致引用中文学位论文时出现英文的[Dissertation]

第2个问题我看了源码`hnuthesis.bst`发现是使用`lang empty$`检查是否中文导致，因此我替换成`langid "chinese" =` 能暂时解决，第1个问题应该出现在`format.names`，但那部分代码太复杂了，无从下手修改，希望作者能够帮忙看看，谢谢！

**Comment by yusanshi** [comment]
抱歉... 其实我没有任何 LaTeX 模板编写/修改经验，这个 repo 的核心内容继承于 <https://github.com/Gwinel/Latex/>。刚才我也试了一下，对语法也不了解，不会弄:face_exhaling::face_exhaling:

**Comment by yakunouyang** [comment]
好吧哈哈哈，我本来想用 [gbt7714-bibtex-style](https://github.com/zepinglee/gbt7714-bibtex-style) 来替换原来的 bibtex style，结果发现湖大用的是最老的 [GB 7714—87](https://github.com/saccohuo/GBT-Standard/blob/master/Others/GB7714-87.doc) 版本，找不到对应的style实现，我过阵子尝试一下能否从GB/T 7714—2005上迁移过来
