### ISSUE TITLE
生成的pdf书签导航有重复

### ISSUE THREAD

**Issue by Aristozhang** [yusanshi/hnuthesis#9]
![捕获](https://user-images.githubusercontent.com/59792633/230297347-ff0eef16-b87c-4995-834f-eff74940145a.PNG)
如图所示，左侧摘要和插图索引等都重复出现！

**Comment by Aristozhang** [comment]
直接下载github代码再上传到overleaf运行报错呀？或者overleaf那个模板可以怎么改一下解决这个问题吗

**Comment by zyt888** [comment]
请问这个问题怎么解决的呀
